### ISSUE TITLE
🍻?

### ISSUE THREAD

**Issue by domgreen** [HuddleEng/octopose#11]
@penderi @george-ayris - lets do a meetup (beer) and we can decide which python meetups we want to talk about this at 👍 
Obvs we will be very productive and this isnt just an excuse for a beer.

**Comment by penderi** [comment]
I think it's necessary and vital for the future of octopyssy

**Comment by george-ayris** [comment]
I fully support this motion

**Comment by penderi** [comment]
What happen?

**Comment by domgreen** [comment]
Nothing yet, needs to be scheduled. #Octopose-Con ...

Will Huddle pay for your travel to the "conference"?

**Comment by penderi** [comment]
OCTOCON

**Comment by penderi** [comment]
Also why travel ? Are we doing this in Berlin?

**Comment by domgreen** [comment]
@penderi 🤪

**Comment by domgreen** [comment]
ping

**Comment by penderi** [comment]
pong. Any progress on this urgent issue?

**Comment by domgreen** [comment]
Kk, currently away but let's arrange Octoconf for mid to late June?

**Comment by domgreen** [comment]
We combining OctoConf with drinks later in the month? @george-ayris @penderi

**Comment by george-ayris** [comment]
Excellent shout. It can include the baton passing ceremony to the next maintainer of octopose!

**Comment by domgreen** [comment]
You mean someone else will do a PR? 😮 Will be pleasantly surprised 😂

**Comment by holytshirt** [comment]
Yeah man, none of us ever going to have beer together 🤣
