### ISSUE TITLE
FR -> make octopose log at a humane level

### ISSUE THREAD

**Issue by penderi** [HuddleEng/octopose#14]
Octopose, Octopose? Octopose!
If only you could for me,
log at a level, 
     that will not bedevil
with too many lines to see

**Comment by penderi** [comment]
in brief - I'd advise not to relay deploy output from each Octopus deploy.
Ideally, I'd see a single line per deploy. If there's an error, a single line reporting it would be perfect.
AND THEN
a simple --verbose flag to output all deploy messages would be the best of both worlds, just with a sensible default

**Comment by domgreen** [comment]
Good idea, the main issue i remember around this is that most people have horrid log levels in their deploys and do not use verbose flags and verbose logging. 
You could attempt to redirect this output to devnull when you run the deployments locally.

```
third_party\\NuGet.exe bla blah blah > /dev/null
```

My initial thoughts on how to get around this :)

**Comment by penderi** [comment]
'twas my thinking too. You can't dictate what they'll do. Perhaps expect to ignore -> pipe to null. But provide flas to override and colelct all stdx.
