### ISSUE TITLE
Projects that has been deployed to an enviroment is not in the generated manifest and is duplicated without project

### ISSUE THREAD

**Issue by george-ayris** [HuddleEng/octopose#15]
This is likely to be a combination of octopose and our internal Octopus configuration.

## Internal repo
`python .\generate_manifest.py -p Babble`
generates
```
{
 "Projects": {
  "Babble": {
   "Packages": [
    "Huddle.Babble.Monitoring.NewRelic",
    "Huddle.Babble.Database",
    "Huddle.Babble.Database",
    "Huddle.Babble.Cli",
    "Huddle.Babble.EventHandlerService",
    "Huddle.BabbleApi",
    "Huddle.Babble.Api.Host",
    "Huddle.ReplyByEmail.HeartbeatMonitorService",
    "Huddle.ReplyByEmail.MailWatcherService",
    "Huddle.ReplyByEmail.ProcessorService",
    "Huddle.Babble.EmailDigestTrigger.Cli",
    "Huddle.Babble.ReferenceDataService.Hacktivator"
   ]
  }
 },
 "StagingLocation": "D:\\dev\\huddle\\StagingLocation"
}
```
`python .\generate_manifest.py -p Babble -e uklive`
generates
```
{
 "Projects": {
  "Babble": {
   "Version": "4.5.223",
   "Packages": [
    "Huddle.Babble.Monitoring.NewRelic",
    "Huddle.Babble.Cli",
    "Huddle.Babble.EventHandlerService",
    "Huddle.BabbleApi",
    "Huddle.Babble.Api.Host",
    "Huddle.ReplyByEmail.HeartbeatMonitorService",
    "Huddle.ReplyByEmail.MailWatcherService",
    "Huddle.ReplyByEmail.ProcessorService",
    "Huddle.Babble.EmailDigestTrigger.Cli",
    "Huddle.Babble.ReferenceDataService.Hacktivator"
   ]
  }
 },
 "StagingLocation": "D:\\dev\\huddle\\StagingLocation"
}
```

Top has two `Huddle.Babble.Database` projects the bottom has neither. Current expectations are that both should have one.

**Comment by domgreen** [comment]
So the first is getting the list of projects from the `steps` section of octopus ... can you check in there to see what you have?
The second is looking at what it thinks has been deployed to `uklive` it either cant find a deployment to `uklive` or that it cant find it at that version.
Can't fully remember how we did this but I would look closer at the steps and find confirmation that we actually have the correct version in live.

**Comment by domgreen** [comment]
The double database may be due to the manual intervention that we originally discussed when doing state based db deployments.

**Comment by penderi** [comment]
+1 that was my guess.
