### ISSUE TITLE
Pipe output from generate_manifest.py to octopose.py

### ISSUE THREAD

**Issue by domgreen** [HuddleEng/octopose#2]
This should be fairly simple ... just write to `StdOut` then get the `octopose.py` to be able to read from `StdIn` (https://docs.python.org/dev/library/argparse.html#nargs).

Probably also makes sense to remove the explicit save to file within the manifest generation here https://github.com/Huddle/octopose/blob/master/generate_manifest.py#L68 and instead pipe the output to a file.

```
generate_manifest.py > manifest.json
```

**Comment by george-ayris** [comment]
Done!
