### ISSUE TITLE
Package failure stops whole deploy.

### ISSUE THREAD

**Issue by holytshirt** [HuddleEng/octopose#34]
Should continue with the next deploy?
Should continues with next package?

**Comment by domgreen** [comment]
Would split into two issues.

Welcome PRs 👍

**Comment by holytshirt** [comment]
Got to make a decision first :) or have a switch

**Comment by george-ayris** [comment]
I think the default should mimic Octopus behaviour and therefore stop the current deploy and continue with the next one (if there is one) and then have some consolidated error reporting at the end.

**Comment by domgreen** [comment]
Mimicking the default is a good shout at least to start as it would be what people using octopus already expect. 
Can't remember the default behaviour ATM
