### ISSUE TITLE
Create GitHub releases

### ISSUE THREAD

**Issue by george-ayris** [HuddleEng/octopose#4]

**Comment by domgreen** [comment]
Depends what you are trying to do here but you can get away without cloning the repo by doing the following:

```
curl -L https://github.com/Huddle/octopose/archive/master.tar.gz | tar zx
```

This will grab master of the repo and unzip locally.

If you want to do a release and cut to a specific version then add releases when you are happy using semver.

**Comment by george-ayris** [comment]
That makes sense. This probably makes a lot more sense to do when we have some tests to run and if there is anything in the repo we don't want in the tar.

**Comment by domgreen** [comment]
Once you have a release you should be able to do something very similar:
```
curl -L https://github.com/Huddle/octopose/tarball/v0.1.0 | tar zx
```

**Comment by george-ayris** [comment]
More thoughts on this are that it would be nice to `pip install` this like the aws cli (https://github.com/aws/aws-cli), which would then give native commands and potentially the ability to do auto-completion. This would require moving configuration to a standard location e.g. `~/.octopose`.

**Comment by domgreen** [comment]
Forgot about `pip install` :p but supplying both would be best tbh and pip install would probably just be fed from the GH release.
As far as config `~/.octopose` is a good idea if you are intending to keep the option for file based config. 
Would be good to move to environment variables as well and allow the option to do either.

**Comment by domgreen** [comment]
Probably break this into two issues `support pip install` and `create GH release`.

**Comment by domgreen** [comment]
@george-ayris can probably close this as well 👍
