### ISSUE TITLE
Name change - I feel py-pose to be a better fit

### ISSUE THREAD

**Issue by penderi** [HuddleEng/octopose#8]
or Octo-py if you'd prefer

**Comment by domgreen** [comment]
Thanks for the suggestion, will "file" it away for later use when we constrain the project to just deploy python apps ;)

**Comment by penderi** [comment]
That's a terrible shame. Especially as Octo-py satisfies the vendor specificity and language choice with a play on the popular plural misconception.

**Comment by domgreen** [comment]
However, `Octopose` leaves us open to change the underlying technology if for instance the tool would be re written in `Go` or `Rust` we would not want to change the name ... `Goctopus` | `OctoRus` is great but breaking dependencies and CI pipelines when renaming is not a great for an OSS project.
