### ISSUE TITLE
A picture is worth a thousand words

### ISSUE THREAD

**Issue by penderi** [HuddleEng/octopose#9]
Need icon. 
Suggestions
http://c8.alamy.com/comp/KCTFG8/concept-of-a-selfie-with-animals-in-the-form-of-an-octopus-posing-KCTFG8.jpg
http://www.wookmark.com/image/74271/baby-octopus-posing-greece-by-stamatisgr 
http://i.dailymail.co.uk/i/pix/2016/05/07/08/33E4B9EE00000578-0-image-m-17_1462606657352.jpg
https://beta.images.theglobeandmail.com/54e/arts/article37828269.ece/BINARY/w620/takashi-folio01nw9.JPG

**Comment by domgreen** [comment]
Love your enthusiasm!

**Comment by penderi** [comment]
Man I actually got excited and then I saw your label. Most of my comments haven't been trolling.

**Comment by domgreen** [comment]
@penderi can you assign it to Alex see if he can get someone to come up with a quick logo?

**Comment by penderi** [comment]
I guess. not sure what the skinny is on these things. Simply ask?
________________________________

**Comment by penderi** [comment]
I have an image that could work well. @george-ayris  is upset by it. I don't want to scare anyone.

**Comment by penderi** [comment]
Wonderful. When do we get the sticker / t-shirts / balaclavas ?

**Comment by domgreen** [comment]
Swimwear?

**Comment by penderi** [comment]
OOoooo. Octo. Pose. Budgie. Smugglers. Can you spot the extra tentacle? ;-)

**Comment by penderi** [comment]
https://budgysmuggleruk.com/pages/custom-swimwear

**Comment by domgreen** [comment]
Why did i click?

**Comment by penderi** [comment]
![image](https://user-images.githubusercontent.com/502314/37402079-1a1704aa-2782-11e8-9633-550a00b6ba68.png)
